### ISSUE TITLE
Import Imsage button appears on startpos trigger 

### ISSUE THREAD

**Issue by l0zthrental** [iAndyHD3/image2gd#1]
![hình ảnh_2023-06-11_194822523](https://github.com/iAndyHD3/image2gd/assets/95627666/3117e7ff-9e78-48e6-ae0b-56d26b90644e)

**Comment by iAndyHD3** [comment]
lmaooooooooooo will fix

**Comment by iAndyHD3** [comment]
fixed in new release, thanks for the report
